/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A1;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        System.out.println("Which encryption method do you want to use?");
        System.out.println("1. Substitution");
        System.out.println("2. Transposition");

        int typeOfMethod = scan.nextInt();
        scan.nextLine();

        System.out.println("\nDo you want to encrypt or decrypt?");
        System.out.println("1. Encrypt");
        System.out.println("2. Decrypt");

        int encryptOrDecrypt = scan.nextInt();
        scan.nextLine();

        System.out.println("Enter a secret key: ");
        String secretKey = scan.nextLine();

        System.out.println("Enter a file to process: ");
        String file = scan.nextLine();

        if (typeOfMethod == 1) {
            if (encryptOrDecrypt == 1) {
                substitutionEncryption(secretKey, file);
            } else if (encryptOrDecrypt == 2) {
                substitutionDecryption(secretKey, file);
            }
        } else if (typeOfMethod == 2) {
            if (encryptOrDecrypt == 1) {
                transpositionEncryption(secretKey, file);
            } else if (encryptOrDecrypt == 2) {
                transpositionDecryption(secretKey, file);
            }
        }
    }

    public static void substitutionEncryption(String key, String file) {
        System.out.println("subEnc");
    }

    public static void substitutionDecryption(String key, String file) {
        System.out.println("subDec");
    }

    public static void transpositionEncryption(String key, String file) {
        System.out.println("tranEnc");
    }

    public static void transpositionDecryption(String key, String file) {
        System.out.println("TranDec");
    }
}
